name: Test & Deploy

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read
    actions: read
    checks: write

jobs:
    test:
        name: Run Vitest Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

    deploy:
        name: Deploy Docker Images
        runs-on: ubuntu-latest
        timeout-minutes: 20
        needs: test
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log into Docker Hub
              uses: docker/login-action@v3
              with:
                  username: daqem
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  build-args: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
                  tags: daqem/projeli:ui
